AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SrcBucketName:
    Type: String
    Default: task1-input-bucket

  DestBucketName:
    Type: String
    Default: task1-output-bucket

Resources:
  SrcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SrcBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Function: !GetAtt MyLambdaFunction.Arn

  DestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestBucketName


  Mys3LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: s3LambdaRole_cloudformation
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: s3ReadSourceBucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource: !Sub 'arn:aws:s3:::${SrcBucketName}/*'
        - PolicyName: s3WriteDestinationBucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*Object'
                Resource: !Sub 'arn:aws:s3:::${DestBucketName}/*'
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogaStream'
                  - 'logs:PutLogEvents'
                Resource: '*'


  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: s3_lambda_cf
      Code:
        S3Bucket: bucketwith-code
        S3Key: lambda_function.zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Role: !GetAtt Mys3LambdaRole.Arn


  S3LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MyLambdaFunction
      Principal:  s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:s3:::${SrcBucketName}
